components {
  id: "villager"
  component: "/world/entities/villager/villager.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"idle-front\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/tilesources/villager/alex/alex-idle.tilesource\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collision"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"box\"\n"
  "  }\n"
  "  data: 2.0\n"
  "  data: 9.333334\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
